"""init

Revision ID: 1f7cfa3470ac
Revises: 
Create Date: 2023-07-02 18:02:47.647843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7cfa3470ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_items',
    sa.Column('saleID', sa.String(length=15), nullable=False),
    sa.Column('gNumber', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('lastChangeDate', sa.DateTime(), nullable=True),
    sa.Column('supplierArticle', sa.String(length=75), nullable=True),
    sa.Column('techSize', sa.String(length=30), nullable=True),
    sa.Column('barcode', sa.String(length=30), nullable=True),
    sa.Column('totalPrice', sa.Numeric(), nullable=True),
    sa.Column('discountPercent', sa.Integer(), nullable=True),
    sa.Column('isSupply', sa.Boolean(), nullable=True),
    sa.Column('isRealization', sa.Boolean(), nullable=True),
    sa.Column('promoCodeDiscount', sa.Numeric(), nullable=True),
    sa.Column('warehouseName', sa.String(length=50), nullable=True),
    sa.Column('countryName', sa.String(length=200), nullable=True),
    sa.Column('oblastOkrugName', sa.String(length=200), nullable=True),
    sa.Column('regionName', sa.String(length=200), nullable=True),
    sa.Column('incomeID', sa.Integer(), nullable=True),
    sa.Column('odid', sa.Integer(), nullable=True),
    sa.Column('spp', sa.Numeric(), nullable=True),
    sa.Column('forPay', sa.Numeric(), nullable=True),
    sa.Column('finishedPrice', sa.Numeric(), nullable=True),
    sa.Column('priceWithDisc', sa.Numeric(), nullable=True),
    sa.Column('nmId', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('isStorno', sa.Integer(), nullable=True),
    sa.Column('sticker', sa.String(), nullable=True),
    sa.Column('srid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('saleID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_items')
    # ### end Alembic commands ###
