"""promoCodeDiscount

Revision ID: 2700608245ed
Revises: 6dc4e1c9814e
Create Date: 2023-07-02 10:01:17.927036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2700608245ed'
down_revision = '6dc4e1c9814e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_items', sa.Column('promoCodeDiscount', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_items', 'promoCodeDiscount')
    # ### end Alembic commands ###
