"""add all the columns

Revision ID: 3a00eed16c71
Revises: 2700608245ed
Create Date: 2023-07-02 10:07:34.850443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a00eed16c71'
down_revision = '2700608245ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_items', sa.Column('warehouseName', sa.String(length=50), nullable=True))
    op.add_column('sales_items', sa.Column('countryName', sa.String(length=200), nullable=True))
    op.add_column('sales_items', sa.Column('oblastOkrugName', sa.String(length=200), nullable=True))
    op.add_column('sales_items', sa.Column('regionName', sa.String(length=200), nullable=True))
    op.add_column('sales_items', sa.Column('incomeID', sa.Integer(), nullable=True))
    op.add_column('sales_items', sa.Column('odid', sa.Integer(), nullable=True))
    op.add_column('sales_items', sa.Column('spp', sa.Numeric(), nullable=True))
    op.add_column('sales_items', sa.Column('forPay', sa.Numeric(), nullable=True))
    op.add_column('sales_items', sa.Column('finishedPrice', sa.Numeric(), nullable=True))
    op.add_column('sales_items', sa.Column('priceWithDisc', sa.Numeric(), nullable=True))
    op.add_column('sales_items', sa.Column('nmId', sa.Integer(), nullable=True))
    op.add_column('sales_items', sa.Column('subject', sa.String(length=50), nullable=True))
    op.add_column('sales_items', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('sales_items', sa.Column('brand', sa.String(length=50), nullable=True))
    op.add_column('sales_items', sa.Column('isStorno', sa.Boolean(), nullable=True))
    op.add_column('sales_items', sa.Column('sticker', sa.String(), nullable=True))
    op.add_column('sales_items', sa.Column('srid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_items', 'srid')
    op.drop_column('sales_items', 'sticker')
    op.drop_column('sales_items', 'isStorno')
    op.drop_column('sales_items', 'brand')
    op.drop_column('sales_items', 'category')
    op.drop_column('sales_items', 'subject')
    op.drop_column('sales_items', 'nmId')
    op.drop_column('sales_items', 'priceWithDisc')
    op.drop_column('sales_items', 'finishedPrice')
    op.drop_column('sales_items', 'forPay')
    op.drop_column('sales_items', 'spp')
    op.drop_column('sales_items', 'odid')
    op.drop_column('sales_items', 'incomeID')
    op.drop_column('sales_items', 'regionName')
    op.drop_column('sales_items', 'oblastOkrugName')
    op.drop_column('sales_items', 'countryName')
    op.drop_column('sales_items', 'warehouseName')
    # ### end Alembic commands ###
