"""add isRealization

Revision ID: 6dc4e1c9814e
Revises: ac86023128d9
Create Date: 2023-07-02 10:00:11.798609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc4e1c9814e'
down_revision = 'ac86023128d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_items', sa.Column('isRealization', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_items', 'isRealization')
    # ### end Alembic commands ###
